# -*- coding: utf-8 -*-
"""Poultry_disease_detection_CNN_IMPROVED_v2 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORLjIEGQfdkP907MJRiF6XyN6v3MoYBw
"""

# ==========================================
# BLOCK 0: ALL NOTEBOOK IMPORTS
# ==========================================
print("📦 Loading all required AI, plotting, and evaluation libraries...")

import os
import random
import numpy as np
import tensorflow as tf
import kagglehub
from tensorflow.keras import models, layers
from tensorflow.keras.applications import EfficientNetB3
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.mixed_precision import set_global_policy
from sklearn.utils.class_weight import compute_class_weight
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

try:
    from google.colab import drive
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# FIX: no seeding previously beyond the dataset split -> non-reproducible runs
SEED = 123
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

# FIX: mixed precision was never enabled. On T4/A100/V100 GPUs this roughly
# 2-3x's training throughput and lets us afford more epochs / a bigger backbone
# in the same wall-clock budget, with negligible accuracy impact.
try:
    set_global_policy('mixed_float16')
    print("⚡ Mixed precision (float16) enabled.")
except Exception as e:
    print(f"Mixed precision not enabled: {e}")

print("✅ All modules imported successfully! Ready to run the pipeline.")

# ==========================================
# BLOCK 1: AUTOMATED DATA PIPELINE & CACHING (OPTIMIZED)
# ==========================================

print("📥 Step 1: Downloading poultry disease images via kagglehub...")
raw_path = kagglehub.dataset_download("kausthubkannan/poultry-diseases-detection")

if 'poultry_diseases' in os.listdir(raw_path):
    directory = os.path.join(raw_path, 'poultry_diseases')
elif 'Poultry_Diseases' in os.listdir(raw_path):
    directory = os.path.join(raw_path, 'Poultry_Diseases')
else:
    directory = raw_path

# SPEED HACK: Reduce to 224. EfficientNetB3 handles 224 perfectly fine and runs ~50% faster.
IMAGE_SIZE = 224
BATCH_SIZE = 32

print(f"📁 Target data folder located at: {directory}")
print("\n🔄 Step 2: Splitting dataset into train / validation / test (70/15/15)...")

train_ds = tf.keras.utils.image_dataset_from_directory(
    directory,
    validation_split=0.3,
    subset="training",
    seed=SEED,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

holdout_ds = tf.keras.utils.image_dataset_from_directory(
    directory,
    validation_split=0.3,
    subset="validation",
    seed=SEED,
    image_size=(IMAGE_SIZE, IMAGE_SIZE),
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
holdout_batches = tf.data.experimental.cardinality(holdout_ds).numpy()
val_ds = holdout_ds.take(holdout_batches // 2)
test_ds = holdout_ds.skip(holdout_batches // 2)

class_counts = {cls: len(os.listdir(os.path.join(directory, cls))) for cls in class_names}
counts = np.array(list(class_counts.values()))
imbalance_ratio = counts.max() / counts.min()

if imbalance_ratio > 1.5:
    labels_expanded = np.concatenate([[i] * c for i, c in enumerate(counts)])
    weights = compute_class_weight(
        class_weight='balanced',
        classes=np.arange(len(class_names)),
        y=labels_expanded
    )
    class_weight_dict = dict(enumerate(weights))
else:
    class_weight_dict = None

cache_dir = "/content/tfcache" if IN_COLAB else "./tfcache"
os.makedirs(cache_dir, exist_ok=True)
for split in ("train", "val", "test"):
    for f in tf.io.gfile.glob(os.path.join(cache_dir, f"{split}*")):
        tf.io.gfile.remove(f)

SHUFFLE_BUFFER = BATCH_SIZE * 8
PREFETCH_BATCHES = tf.data.AUTOTUNE # Let TF optimize this now that we resized images

# SPEED HACK: Cache the training dataset to disk!
train_ds = train_ds.cache(os.path.join(cache_dir, "train")).shuffle(SHUFFLE_BUFFER, seed=SEED).prefetch(buffer_size=PREFETCH_BATCHES)
val_ds = val_ds.cache(os.path.join(cache_dir, "val")).prefetch(buffer_size=PREFETCH_BATCHES)
test_ds = test_ds.cache(os.path.join(cache_dir, "test")).prefetch(buffer_size=PREFETCH_BATCHES)

print(f"\n✅ Success! Loaded {len(class_names)} classification classes: {class_names}")

"""SHOW RANDOM SAMPLES FROM DATASET"""

# ==========================================
 #SHOW RANDOM SAMPLES FROM DATASET
# ==========================================


print("🎲 Picking 9 completely random images from the dataset to inspect...")

# 1. Unbatch the dataset to look at single individual images rather than chunks of 32
# We take 5 batches to give us a good pool of random pictures to choose from
all_images = []
all_labels = []

for images, labels in train_ds.take(5):
    all_images.extend(images.numpy())
    all_labels.extend(labels.numpy())

# 2. Pick 9 random indices from our pool
total_collected = len(all_images)
random_indices = random.sample(range(total_collected), 9)

# 3. Plot the 3x3 grid
plt.figure(figsize=(12, 12))

for i, idx in enumerate(random_indices):
    ax = plt.subplot(3, 3, i + 1)

    # Convert image tensor back to standard displayable pixels
    img = all_images[idx].astype("uint8")
    label_num = all_labels[idx]
    actual_disease = class_names[label_num]

    plt.imshow(img)
    plt.title(f"Class: {actual_disease}\n(Index: {idx})", fontsize=11, color="darkgreen", weight="bold")
    plt.axis("off")

plt.tight_layout()
plt.show()

# FIX: all_images / all_labels holds ~5 full batches of decoded 300x300
# images as a plain Python list (uncompressed, outside tf.data's cache) for
# the rest of the notebook's lifetime unless explicitly freed. Small on its
# own, but it adds up on top of the dataset cache and training buffers -
# free it now since this cell's only job was the one-off plot above.
import gc
del all_images, all_labels
gc.collect()

"""# Problem Statement:
Poultry industry faces economic losses due to various diseases. 'Salmonella', 'Newcasttle', 'Coccidiosis' are major common diseases and it is estimated that the major loss occurred in poultry industry is due to these diseases.
"""

# ==========================================
# BLOCK 2: TRANSFER LEARNING MODEL (EfficientNetB3) & COMPILATION
# ==========================================

print("🏗️ Building EfficientNetB3 transfer-learning model...")

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip(mode="horizontal_and_vertical"),
    layers.RandomRotation(factor=0.2),
    layers.RandomZoom(0.15),
    layers.RandomContrast(0.15),
    layers.RandomTranslation(0.1, 0.1),
], name="data_augmentation")

base_model = EfficientNetB3(
    include_top=False,
    weights="imagenet",
    input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3),
    pooling=None
)
base_model.trainable = False  # Phase 1: freeze backbone, train only the new head

inputs = tf.keras.Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 3))
x = data_augmentation(inputs)
x = preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.4)(x)
# IMPROVEMENT: an extra wider dense block gives the head more room to combine
# EfficientNetB3's 1536-dim features before collapsing to the class logits.
# BatchNorm + L2 + Dropout keep it from just overfitting on that extra capacity.
x = layers.Dense(512, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.4)(x)
x = layers.Dense(256, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x = layers.Dropout(0.3)(x)
# Output layer stays float32 even under mixed precision, for numerical stability
outputs = layers.Dense(len(class_names), activation='softmax', dtype='float32')(x)

CNN = models.Model(inputs, outputs, name="EfficientNetB3_Poultry")

# IMPROVEMENT: label smoothing.
# SparseCategoricalCrossentropy doesn't expose label_smoothing, so we wrap it:
# one-hot the sparse integer label internally, then delegate to
# CategoricalCrossentropy(label_smoothing=...). This is a drop-in loss that
# still consumes the SAME sparse-int-label datasets the rest of the notebook
# already builds/evaluates with - no changes needed anywhere else.
# Why it helps push toward 98%: with only a few disease classes and a
# pretrained backbone, the model can become over-confident on training data
# (softmax pushed to ~0/1) which hurts generalization to the held-out test
# set. Smoothing the targets slightly (0.9 / 0.1 instead of 1.0 / 0.0) keeps
# gradients from over-fitting samples the model has already "solved",
# typically buying a small but real bump in test accuracy and better-calibrated
# confidences.
NUM_CLASSES = len(class_names)

def label_smoothed_loss(y_true, y_pred, label_smoothing=0.1, num_classes=NUM_CLASSES):
    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), depth=num_classes)
    return tf.keras.losses.categorical_crossentropy(
        y_true_oh, y_pred, label_smoothing=label_smoothing
    )

CNN.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss=label_smoothed_loss,
    metrics=['accuracy']
)

print("✅ Model built and compiled successfully!")
CNN.summary()

"""# loading data"""

# ==========================================
# BLOCK 3: TWO-PHASE TRAINING (FEATURE EXTRACTION + FINE-TUNING)
# ==========================================

if IN_COLAB:
    print("🔗 Mounting your Google Drive storage for automated checkpoints...")
    drive.mount('/content/drive', force_remount=True)
    backup_folder = "/content/drive/MyDrive/Poultry_AI_Project"
else:
    backup_folder = "./Poultry_AI_Project"

os.makedirs(backup_folder, exist_ok=True)

# IMPROVEMENT: patience bumped 5 -> 7. With more fine-tuning epochs and a
# cosine-decay schedule (below) the val_loss curve can plateau for a few
# epochs before the smaller LR steps start paying off again - stopping too
# early throws away those later gains.
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=7,
    restore_best_weights=True
)

checkpoint_callback = ModelCheckpoint(
    filepath=os.path.join(backup_folder, "poultry_disease_model_best.keras"),
    monitor="val_accuracy",
    save_best_only=True,
    verbose=1
)

# NOTE: ReduceLROnPlateau directly overwrites optimizer.learning_rate, which
# only works when the optimizer was built with a plain float learning rate.
# Phase 1's optimizer (Adam(1e-3), set back in Block 2) is a plain float, so
# it's used there. Phase 2's optimizer is rebuilt with a CosineDecay
# schedule (below), and schedule-based learning rates are NOT settable -
# combining the two raises:
#   TypeError: This optimizer was created with a `LearningRateSchedule`...
# So we keep two callback lists: Phase 1 keeps reduce_lr, Phase 2 drops it
# (the cosine schedule already handles annealing the LR down, so it's
# redundant there anyway).
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=2,
    min_lr=1e-7,
    verbose=1
)

callbacks_phase1 = [early_stopping, checkpoint_callback, reduce_lr]
callbacks_phase2 = [early_stopping, checkpoint_callback]

# IMPROVEMENT: phase 1 epochs 15 -> 20. The head (freshly-initialized Dense
# layers) needs enough epochs to actually converge before we start touching
# the pretrained backbone weights in phase 2; EarlyStopping still cuts it
# short if it converges sooner, so this only helps, never hurts runtime.
PHASE1_EPOCHS = 20

print("\n🚀 PHASE 1: Training classification head (backbone frozen)...")
training_his = CNN.fit(
    train_ds,
    validation_data=val_ds,
    epochs=PHASE1_EPOCHS,
    class_weight=class_weight_dict,
    callbacks=callbacks_phase1
)

print("\n🔧 PHASE 2: Fine-tuning top layers of EfficientNetB3...")
# IMPROVEMENT: unfreeze the top 50% of the backbone instead of top 30%.
# More of the backbone gets to specialize on fecal-image disease texture
# instead of staying generic ImageNet features - this is the single biggest
# lever for closing the last few points to ~98%, since it lets mid-level
# filters (not just the very last block) adapt to this specific domain.
base_model.trainable = True
fine_tune_at = int(len(base_model.layers) * 0.5)
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

FINE_TUNE_EPOCHS = 30
steps_per_epoch = tf.data.experimental.cardinality(train_ds).numpy()

# IMPROVEMENT: cosine-decay LR schedule instead of a flat 1e-5.
# A constant fine-tuning LR either wastes early epochs (too small) or
# destabilizes late epochs (too large for the last mile). Cosine decay starts
# at a slightly higher 3e-5, giving the newly-unfrozen mid-layers a real
# chance to move, then smoothly anneals toward ~0 so the last few epochs are
# fine, precise updates - exactly what's needed to squeeze out the last
# couple of accuracy points.
lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=3e-5,
    decay_steps=steps_per_epoch * FINE_TUNE_EPOCHS,
    alpha=0.01  # decays down to ~1% of the initial LR, not all the way to 0
)

# IMPROVEMENT: AdamW (decoupled weight decay) instead of plain Adam for the
# fine-tuning phase - extra regularization specifically while the backbone
# weights are unfrozen and most at risk of overfitting the (relatively) small
# poultry dataset.
CNN.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=lr_schedule, weight_decay=1e-5),
    loss=label_smoothed_loss,
    metrics=['accuracy']
)

total_epochs = training_his.epoch[-1] + 1 + FINE_TUNE_EPOCHS

training_his_fine = CNN.fit(
    train_ds,
    validation_data=val_ds,
    epochs=total_epochs,
    initial_epoch=training_his.epoch[-1] + 1,
    class_weight=class_weight_dict,
    callbacks=callbacks_phase2
)

print("\n🎉 Training session wrapped up successfully!")

"""Plot Training History (Loss & Accuracy Curves)"""

# ==========================================
# BLOCK 4: PLOT TRAINING HISTORY CURVES (SAFE VERSION)
# ==========================================
import matplotlib.pyplot as plt

print("📊 Plotting accuracy and loss trends from training...")

# Initialize empty lists to safely gather whatever history exists
acc = []
val_acc = []
loss = []
val_loss = []
fine_tune_start = 0

# Check if Phase 1 history is in memory
if 'training_his' in locals() or 'training_his' in globals():
    acc.extend(training_his.history.get('accuracy', []))
    val_acc.extend(training_his.history.get('val_accuracy', []))
    loss.extend(training_his.history.get('loss', []))
    val_loss.extend(training_his.history.get('val_loss', []))
    fine_tune_start = len(acc)

# Check if Phase 2 history is in memory
if 'training_his_fine' in locals() or 'training_his_fine' in globals():
    acc.extend(training_his_fine.history.get('accuracy', []))
    val_acc.extend(training_his_fine.history.get('val_accuracy', []))
    loss.extend(training_his_fine.history.get('loss', []))
    val_loss.extend(training_his_fine.history.get('val_loss', []))

# Plot if we found any data
if not acc:
    print("⚠️ Warning: No training history found in memory. You may need to re-run Block 3.")
else:
    epochs_range = range(len(acc))
    plt.figure(figsize=(15, 5))

    # --- Accuracy Plot ---
    plt.subplot(1, 2, 1)
    plt.plot(epochs_range, acc, label='Training Accuracy', color='teal', linewidth=2)
    plt.plot(epochs_range, val_acc, label='Validation Accuracy', color='darkorange', linewidth=2)
    if 0 < fine_tune_start < len(acc):
        plt.axvline(x=fine_tune_start, color='gray', linestyle='--', label='Fine-tuning starts')
    plt.title('Model Accuracy Progress')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend(loc='lower right')
    plt.grid(True, alpha=0.3)

    # --- Loss Plot ---
    plt.subplot(1, 2, 2)
    plt.plot(epochs_range, loss, label='Training Loss', color='teal', linewidth=2)
    plt.plot(epochs_range, val_loss, label='Validation Loss', color='darkorange', linewidth=2)
    if 0 < fine_tune_start < len(loss):
        plt.axvline(x=fine_tune_start, color='gray', linestyle='--', label='Fine-tuning starts')
    plt.title('Model Loss Progress')
    plt.xlabel('Epochs')
    plt.ylabel('Loss Value')
    plt.legend(loc='upper right')
    plt.grid(True, alpha=0.3)

    plt.show()

# ==========================================
# BLOCK 4b: FINAL UNBIASED TEST-SET EVALUATION (FULL AUTO-RECOVERY)
# ==========================================

import os
import random
import numpy as np
import tensorflow as tf
import kagglehub

# 1. AUTO-RECOVER DATASET PIPELINE & CLASS NAMES IF SESSION WAS WIPED
if 'test_ds' not in locals() and 'test_ds' not in globals():
    print("⚠️ Session restarted: Rebuilding test dataset pipeline...")
    SEED = 123
    IMAGE_SIZE = 224 if os.path.exists("./tfcache") or os.path.exists("/content/tfcache") else 300
    BATCH_SIZE = 32

    raw_path = kagglehub.dataset_download("kausthubkannan/poultry-diseases-detection")
    if 'poultry_diseases' in os.listdir(raw_path):
        directory = os.path.join(raw_path, 'poultry_diseases')
    elif 'Poultry_Diseases' in os.listdir(raw_path):
        directory = os.path.join(raw_path, 'Poultry_Diseases')
    else:
        directory = raw_path

    holdout_ds = tf.keras.utils.image_dataset_from_directory(
        directory,
        validation_split=0.3,
        subset="validation",
        seed=SEED,
        image_size=(IMAGE_SIZE, IMAGE_SIZE),
        batch_size=BATCH_SIZE
    )

    train_temp = tf.keras.utils.image_dataset_from_directory(
        directory, validation_split=0.3, subset="training", seed=SEED,
        image_size=(IMAGE_SIZE, IMAGE_SIZE), batch_size=BATCH_SIZE
    )
    class_names = train_temp.class_names

    holdout_batches = tf.data.experimental.cardinality(holdout_ds).numpy()
    test_ds = holdout_ds.skip(holdout_batches // 2).prefetch(buffer_size=tf.data.AUTOTUNE)
    print("✅ Test dataset and class names successfully restored!")

# 2. DEFINE LOSS FUNCTION FOR MODEL LOADING
NUM_CLASSES = len(class_names)
def label_smoothed_loss(y_true, y_pred, label_smoothing=0.1, num_classes=NUM_CLASSES):
    y_true_oh = tf.one_hot(tf.cast(y_true, tf.int32), depth=num_classes)
    return tf.keras.losses.categorical_crossentropy(y_true_oh, y_pred, label_smoothing=label_smoothing)

# 3. AUTO-RECOVER MODEL FROM GOOGLE DRIVE IF NOT IN MEMORY
if 'CNN' not in locals() and 'CNN' not in globals():
    print("⚠️ Re-loading saved model checkpoint from Google Drive...")
    in_colab = os.path.exists('/content/drive')
    backup_folder = "/content/drive/MyDrive/Poultry_AI_Project" if in_colab else "./Poultry_AI_Project"
    checkpoint_path = os.path.join(backup_folder, "poultry_disease_model_best.keras")

    if os.path.exists(checkpoint_path):
        try:
            CNN = tf.keras.models.load_model(
                checkpoint_path,
                custom_objects={'label_smoothed_loss': label_smoothed_loss}
            )
        except Exception:
            CNN = tf.keras.models.load_model(checkpoint_path, compile=False)
            CNN.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
        print("✅ Best trained model loaded into memory!")
    else:
        raise FileNotFoundError(f"❌ Could not find saved model at '{checkpoint_path}'.")

# 4. EVALUATE MODEL ON TEST SET
print("\n🧪 Evaluating on the held-out TEST set (never used during training)...")
test_loss, test_accuracy = CNN.evaluate(test_ds, verbose=1)
print(f"\n✅ Final Test Accuracy (single-pass): {test_accuracy*100:.2f}%")
print(f"✅ Final Test Loss: {test_loss:.4f}")

# 5. TEST-TIME AUGMENTATION (TTA)
def tta_predict(model, images, n_aug=4):
    preds = model.predict(images, verbose=0)
    preds_flip = model.predict(tf.image.flip_left_right(images), verbose=0)
    avg = (preds + preds_flip) / 2.0
    if n_aug >= 4:
        preds_bright_up = model.predict(tf.image.adjust_brightness(images, 0.05), verbose=0)
        preds_bright_down = model.predict(tf.image.adjust_brightness(images, -0.05), verbose=0)
        avg = (avg * 2 + preds_bright_up + preds_bright_down) / 4.0
    return avg

print("\n🔁 Re-scoring the test set with Test-Time Augmentation (avg over flips/brightness)...")
tta_correct = 0
tta_total = 0
for images, labels in test_ds:
    avg_preds = tta_predict(CNN, images)
    batch_preds = np.argmax(avg_preds, axis=1)
    tta_correct += int(np.sum(batch_preds == labels.numpy()))
    tta_total += labels.shape[0]

tta_accuracy = tta_correct / tta_total
print(f"✅ Final Test Accuracy (with TTA): {tta_accuracy*100:.2f}%")

"""### Advanced Evaluation (F1-Score, Confusion Matrix & Summary Report)"""

# ==========================================
# BLOCK 5: CONFUSION MATRIX & F1-SCORE REPORT (SELF-CONTAINED)
# ==========================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

print("🧠 Collecting predictions from the TEST dataset (with TTA)...")

all_true_labels = []
all_predicted_labels = []

for images, labels in test_ds:
    all_true_labels.extend(labels.numpy())
    preds = tta_predict(CNN, images)
    batch_predictions = np.argmax(preds, axis=1)
    all_predicted_labels.extend(batch_predictions)

y_true = np.array(all_true_labels)
y_pred = np.array(all_predicted_labels)

print("✅ Predictions completed. Generating metrics dashboards...\n")
print("-" * 60)
print("             Poultry Classification Analytics Report")
print("-" * 60)

print(classification_report(y_true, y_pred, target_names=class_names))
print("-" * 60)

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names,
    cbar=False
)
plt.title('Poultry Disease Confusion Matrix Tracker', fontsize=14, pad=12)
plt.xlabel('Predicted Disease Class Labels', fontsize=12, labelpad=10)
plt.ylabel('True Dataset Disease Labels', fontsize=12, labelpad=10)
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# ==========================================
# FINAL BLOCK: VISUAL PREDICTION INSPECTION
# ==========================================
print("🔮 Extracting a test batch to visually inspect model predictions...")

plt.figure(figsize=(20, 20))

for img, label in test_ds.take(1):
    # IMPROVEMENT: use TTA here too, so the confidences shown match the
    # TTA-based accuracy reported above rather than a plain single pass.
    batch_prediction = tta_predict(CNN, img)

    for i in range(16):
        ax = plt.subplot(4, 4, i + 1)

        actual_label = class_names[label[i].numpy()]
        predicted_label = class_names[np.argmax(batch_prediction[i])]
        confidence = round(np.max(batch_prediction[i]) * 100, 2)

        plt.imshow(img[i].numpy().astype('uint8'))

        text_color = "green" if actual_label == predicted_label else "red"

        plt.title(
            f"Actual: {actual_label}\nPredicted: {predicted_label}\nConfidence: {confidence}%",
            color=text_color,
            fontsize=10,
            weight="bold"
        )
        plt.axis("off")

plt.tight_layout()
plt.show()